version: 0.2
phases:
  install:
    commands:
      - node --version
      - npm --version
      - npm install
  build:
    commands:
      - npm run build
      - npm run cdk synth -- -o dist
      - npm run cdk bootstrap aws://058632605534/us-east-1
      - npm run cdk deploy -- --require-approval never
artifacts:
  files:
    - dist/*