version: 0.2
phases:
  install:
    commands:
      - node --version
      - npm --version
      - npm install
  build:
    commands:
      - npm run build
      - npm run cdk synth -- -o dist
      - npm run cdk bootstrap
      - npm run cdk diff -- --require-approval never
      - npm run cdk deploy -- --require-approval never
artifacts:
  files:
    - dist/*