version: 0.2
phases:
  install:
    commands:
      - node --version
      - npm --version
      - npm install
      - npm run build
      - npm run cdk synth -- -o dist
artifacts:
  files:
    - dist/*